### ISSUE TITLE
Is it possible to block tags with !important styles?

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardBrowserExtension#1078]

**Comment by ameshkov** [comment]
Sorry for the late reply.

AG styles will have higher priority in the new Chrome version (when they finally merge the usercss patch).
Also, it already has higher priority in the current FF version.

Moreover, instead of basic element-hiding rules you can try another approach, use ExtCss rules: `#?#banner`. In this case the styles will be applied with Javascript and override existing styles.
