### ISSUE TITLE
$csp rules must be disabled if there's a document-level exception applied to the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1093]
See the full spec here:
https://github.com/AdguardTeam/CoreLibs/issues/15

This part is new:

* `@@||example.org^$document` or `@@||example.org^$urlblock` — disables all the `$csp` rules on all the pages matching the rule pattern.

**Comment by maximtop** [comment]
To test this issue go to the page https://maximtop.github.io/csp-rules/
You should see images
in the user's rules add
`||maximtop.github.io^$csp=img-src 'none'`

reload the page, images won't load
add rule
`@@||maximtop.github.io^$urlblock`
or
`@@||maximtop.github.io^$document`
reload the page
images should present again on the page because whitelist rules with `$urlblock` or `$document` modifier cancel block rules
