### ISSUE TITLE
Self-destructing first-party cookies breaks Google authentication

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1182]
See here:
https://uploads.adguard.com/up04_5hbpl_Sign_in_-_Google_Accounts.png

**Comment by maximtop** [comment]
in order to repeat:
1. turn off all stealth mode options
2. turn on `Self-destructing third-party cookies` option
3. decrease time to 10 minutes
4. log out from the gmail.com
5. try to log in back to the gmail.com
There shouldn't appear cookies mismatch notification

Check all steps for `Self-destructing first-party cookies (not recommended)` option too

**Comment by karina-archazh** [comment]
Issue still persist with third-party cookie low settings
