### ISSUE TITLE
Filtering rules limitations (custom filter, user filter)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1196]
1. Custom filters must not support powerful modifiers ($replace and JS) unless they are explicitly enabled by the user filter (there should be a "Trusted" checkbox in the custom filter dialog)
2. Change the CSS rules validation process and discard those with `url` in the style text

`[ ] Trusted filter`
`Filters marked as trusted can use powerful filtering rules modifiers which can be dangerous in the wrong hands. Do not check this box unless you fully trust it.`

Pre-installed filters are marked as trusted by default (as we perform validation on the server-side).

**Comment by maximtop** [comment]
Add filters to the custom group
1. With trusted checkbox checked
https://maximtop.github.io/custom-rules/test-trusted-rules.txt
2. Without trusted checkbox checked
https://maximtop.github.io/custom-rules/test-untrusted-rules.txt

Go to the example.org
You should see in console.log
`test trusted rules`

Also there are replace rules but they work only in the Firefox
Add this custom filters to the extension for Firefox
Open `example.org`
You should find on the screen that `Example Domain` replaced to `trusted Domain`

In order to test that css rule with url is not working
Go to the page
https://maximtop.github.io/custom-rules/

Add css rule 

`maximtop.github.io#$#div.test-css {background: url('https://placekitten.com/g/300/300')}`

This rule won't be added to the all list of rules and won't change square block background to the image

If you'll add this rule in will change square block background to the red

`maximtop.github.io#$#div.test-css {background: red}`
