### ISSUE TITLE
Add a validity checking for rules with domain modifier

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1242]
@AdamWr commented on [Sun Jan 06 2019](https://github.com/AdguardTeam/FiltersCompiler/issues/38)

Rules like these:
`|http*$domain=|example.org`
`|http*$script,domain=|example.org`
should be treated as invalid or converted to:
`|http*$domain=example.org`
`|http*$script,domain=example.org`
otherwise they are applied to all websites due to `domain=|`

**Comment by maximtop** [comment]
In order to check if the issue is resolved
You should turn off all filters and remove all user filters, and then add rules like this
`|http*$domain=|`
`|http*$domain=|example.org`
`|http*$script,domain=|example.org`

After this, you can check in the console of background page, that these rules weren't added to the request filter

You will find there message
`Finished request filter initialization... Rules count: 0`

But if you'll add rules:
`|http*$domain=example.org`
`|http*$domain=example.org|test.org`

Then there will be a message that 2 rules were added.
`Finished request filter initialization... Rules count: 2`
