### ISSUE TITLE
[Question] Difference

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardBrowserExtension#1278]
What is the difference between using `AG_onLoad()` and `!function(){}()` in javascript rules? (Developers of filters don't know exactly.)

**Comment by maximtop** [comment]
Hi, @oleedd 
Where did you find `!function(){}()` in javascript rules?
Also, you can information about iife functions in this article: https://en.wikipedia.org/wiki/Immediately_invoked_function_expression

**Comment by oleedd** [comment]
Thanks. It was interesting to read.
`!function(){}()` is sometimes used in filters.
I want to know the difference in stages of document loading and execution js code of document (before or after rules will work).
Also where I can read about all `AG_` properties?

**Comment by ameshkov** [comment]
1. I want to know the difference in stages of document loading and execution js code of document (before or after rules will work).

In the browser extension, the timing is not definite due to the limitations of the extensions SDK. We're trying to execute them as soon as possible, but we can't guarantee that they'll be executed before the page scripts.

2. Regarding `AG_` props, we're migrating to the new scriptlets syntax anyway. In the future, JS rules will be allowed in a limited subset of filters (or even in the user filter only):
https://github.com/AdguardTeam/CoreLibs/issues/664

The current `AG_` functions are defined here:
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/general_js_api.txt

Also, `AG_defineProperty` is quite huge, and it'd be easier to inspect the source project instead:
https://github.com/AdguardTeam/deep-override

**Comment by oleedd** [comment]
Is there a github page for `AG_abortInlineScript`?

**Comment by ameshkov** [comment]
@oleedd `AG_abortInlineScript` is rather simple, it just uses the `AG_defineProperty` call to insert itself inside a script and abort it's execution.

**Comment by oleedd** [comment]
I have seen examples in filters.
Need to use a selector for script element. Right?
So it can stop any script. Only a script or any function by its name too?

**Comment by AdamWr** [comment]
If I'm not wrong it should aborts a function.
In first part you need to use a regex (with content of the script), in second part a window's property used by script.
`#%#AG_abortInlineScript(/regex/, 'window.Property');`

**Comment by oleedd** [comment]
Window's property used by script - what is meant here?

**Comment by AdamWr** [comment]
For example `window.Promise`, `window.Math`, `window.document`, `window.addEventListener` etc., which are used by inline script.

**Comment by oleedd** [comment]
Why is it need? For exact matching if regex finds several results?

**Comment by oleedd** [comment]
.

**Comment by oleedd** [comment]
Can't unite these masks ~www3.site.com,~www4.site.com into one.
~*.site.com doesn't work. It also doesn't unblock "www" sites.
Any way to do this or it is a bug?
