### ISSUE TITLE
Statistics flushed after browser restart (randomly)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardBrowserExtension#1341]
Steps to reproduce:

1. Chrome/Firefox launch - install 3.0.8 AdG extension
2. Open google.com/ya.ru and check what's counted in statistics, for example (Blocked: 5, Total: 5)
3. Force Quit browser Chrome/Firefox and open it again
4. Visit google.com/ya.ru and see that statistics menu is still showing a previous count

### Your environment

* AdGuard AdBlocker extension version: 3.0.8
* Environment name and version: Chrome 74.0.3729.6 (Official Build) dev (64-bit) / Firefox 65.0.1

**Comment by ameshkov** [comment]
Assigned to 3.1

**Comment by maximtop** [comment]
Stats in the Firefox can be wrong because we save them in the local storage once in 60 sec.

Instructions for QA
In order to repeat you should
1. install the extension
2. browse more than 60 sec
3. remember total stats number
4. turn off browser (cmd + q on macOS)
5. turn on browser
6. statistic should never be reset to the 0 and should be equal to the remembered number or lower than it was but not 0.

Sometimes extension local storage can initialize more than 5 sec, during this time if you click to the icon, a popup window should notify you that extension is unavailable.
After a while when the extension will be available statistics data shouldn't be reset, and the number should correspond to the remembered one.
