### ISSUE TITLE
Unable to export settings on Edge

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#1438]
### Steps to reproduce
1. Install the extension on MS Edge (non-Chromium)
2. Attempt to export settings
3. When clicked, settings file will be opened inside browser without receiving a save prompt

### Expected behavior
Should "download" exported settings file

### Actual behavior
Settings file open in browser instead

<details><summary>Screen recording:</summary>
Available in ticket №1387305
</details>

### Your environment

* AdGuard AdBlocker extension version: 3.2.1, 3.2.2
* Environment name and version: Edge (non-Chromium) 18.18362
* Filters you use in AdGuard: Not applicable
* Any other browser extensions you have installed: None

**Comment by maximtop** [comment]
This happens due to the edge ~~bug~~ special behavior.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8178877/

Seems that this won't be fixed in the near future. 

Nevertheless, after clicking to the `Export settings` button, you can manually copy page content and save it in the editor as a JSON file.
