### ISSUE TITLE
Improve the extension accessibility for visually impaired users 

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardBrowserExtension#1456]
It seems that #953 was not fixed.

> Неясно когда та или иная функция активированы по нажатию на неё.
программа экранного доступа проговаривает "по щелчку".

**Comment by SoLenny** [comment]
Some more details:
1. When you hover over clickable elements pronounces the name + word "link".
2. When you open the extension settings page, it utters the link completely.
3. When you turn on or turn off a function, it first says the full name, then "the flag is checked - not checked." The next time you turn it on or off (without moving the cursor), it only says “checked” or “checked”.
4. Due to the non-linear location of the functional, when using input gestures, the voice assistant jumps by name.
