### ISSUE TITLE
A script in the extension "AdGuard Adblocker" is causing Firefox to slow down.

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardBrowserExtension#1572]
- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.3.8
  
- **Browser and version:** Firefox 72.0.1 (64 bit)
  
- **Operating system and version:** Windows 10

- **Filters you use in AdGuard:** Base,Social,Annoyance,Tracking Protection,Turkish,NoCoin

- **Stealth Mode settings:** Enabled
  
- **Other browser extensions:**
 

### Actual Behavior

https://m.donanimhaber.com/haberler/Yurt-disi-cikis-harci-zamlaniyor-iMEi-kaydinda-yeni-donem.htm?139015496?139016179

The page freezes and Firefox gives you a warning.

**A script in the extension "AdGuard Adblocker" is causing Firefox to slow down.**

### Screenshots

<details><summary>Screenshot:</summary>

![ad](https://user-images.githubusercontent.com/34379403/72225743-ff6fb200-3599-11ea-8327-f72e97aafa4c.png)

</details>

**Comment by ameshkov** [comment]
Could you please check if this is caused by some filter list?
What happens if you disable filter lists one by one?

And one more question: do you have "send ad usage stats" enabled or filtering log open?
If you do, AdGuard changes the way cosmetic rules are added and uses quite a slow script to track which cosmetic rules are applied to the page.

**Comment by PentagramTr** [comment]
> And one more question: do you have "send ad usage stats" enabled or filtering log open?

Yes, "send ad usage stats"" option is on.
But I close this.It doesn't reproduce right now.
Thank you.
