### ISSUE TITLE
$genericblock,generichide issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1580]
Original issue starts from this message: https://github.com/AdguardTeam/AdguardFilters/issues/43606#issuecomment-576069372
@kriegaex

**Comment by kriegaex** [comment]
Thanks @maximtop for several remote sessions in order to find the problem cause.

**Findings:**
* In the end we found a website-specific user rule with a syntax error in my list. Somehow it derailed the rest of the filtering process for the corresponding website.

**Learnings / To do:**
* Syntax errors in rules can always happen.
* They should not stop other rules from working correctly, the filtering process should just ignore faulty rules gracefully.
* In addition to that it would be nice if the browser extension would refuse saving and/or at least show comprehensive error messages for faulty rules so as to make the user aware of problems and help him fix them.

**Comment by maximtop** [comment]
I've created #1598

**Comment by kriegaex** [comment]
Thanks @maximtop, but that ticket only addresses a minor issue. As I said, syntax errors in rules can always happen, theoretically also in curated lists, also in manually edited and imported ones etc. There is not ticket for the second and third bullet points in my list above, especially the second one about gracefully handling faulty rules.
