### ISSUE TITLE
Add Stealth-mode settings to the export list

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#1732]
**The filter file is not deleted after turning off the filter:**

I am using AdGuard AdBlocker version 3.5.23 on EDGE 87.
I've noticed that, after installing this extension, it automatically downloads the default filter files. Those files were unnecessary for me because I have not (never) ever visited those sites, so I proceeded to disable all the default filters and use the filtering rule of only me.
However, I have noticed that although I have disabled those filters, the filter files of those filters are not deleted at all (see image). This makes the extension use more resources, making the browser open more slowly.
![The filter file has not been deleted](https://user-images.githubusercontent.com/20223064/101899978-48344e80-3be1-11eb-908d-1b8c2d95a0bb.png)
So I hope there will be a solution of getting rid of these files or in the next update which will completely disable downloading of the default filters.

**"Export setting" does not export data of the "Privacy" setting:**
The "Export setting" function will export all settings but there is no setting data for "Privacy".
So please fix this problem!

**Comment by Chinaski1** [comment]
Hello there!

1) We do not remove filters after they are disabled.
Could you be more specific about what is shown in your screenshot?
2) We will add the ability to export stealth-mode settings in an upcoming update.

**Comment by Cutetlaem** [comment]
> Hello there!
> 
> 1. We do not remove filters after they are disabled.
>    Could you be more specific about what is shown in your screenshot?
> 2. We will add the ability to export stealth-mode settings in an upcoming update.

Sorry for the late reply,
> 1. We do not remove filters after they are disabled.
>    Could you be more specific about what is shown in your screenshot?

In that picture is the default filter file downloaded, there are about 5-6 such files in the extension's data folder. When I delete those files, the extension will crash, need to download again.
Most of the filters in there are useless to me, but keeping them will increase the size of the extension a lot, use more resources, and having more filters will make the website load slower.
> 2. We will add the ability to export stealth-mode settings in an upcoming update.

Yes. Thanks, for now the extension is unable to export stealth-mode setting data. Let's add it!
I think an upcoming update, instead of automatically downloading the default filter file after installing the extension, ask users if they want to download it? Because not everyone needs it! Or at least delete the filter file after the user has disabled the filter.
In addition, the extension still cannot block BlockAdBlock scripts (the scripts are directly in the page). Don't know if there is a solution to this problem?

**Comment by chirag127** [comment]
> 2. We will add the ability to export stealth-mode settings in an upcoming update.

Is it work in progress . I think many updates have come since this was commented .
