### ISSUE TITLE
Merge the distribution accounts

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#1775]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

<img width="1797" alt="image" src="https://user-images.githubusercontent.com/25068100/111488714-c866d480-8739-11eb-94c6-7dd82b1ff66d.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/25068100/111488306-69a15b00-8739-11eb-8c3d-48af3d72b2a8.png">

### Proposed Solution

Merge distribution accounts for Google Chrome and Microsoft Edge and implement unified name "Adguard Software Ltd"

**Comment by ameshkov** [comment]
Edge - same problem as Apple, can't change without re-uploading and losing everything.
Chrome - they are on the same account, but due to the CWS bug it does not show website domain, it simply does not save our changes to the listing.

**Comment by sergerosenthaler** [comment]
@ameshkov After reading your detailed answers I have to say, those big tech companies are producing a lot of sh***t:-)

**Comment by ameshkov** [comment]
Yeah :( I must say our case (account country change) is rather rare, probably does not happen too often and that's why they don't care. Does not excuse outright bugs.

And Apple's thing with iCloud entitlement blocking from the app transfer is an absolute champion. We disabled it 3 years ago, but it does not matter, it's enough that it was enabled in the past :)
