### ISSUE TITLE
Remove `Do Not Track` Feature

### ISSUE THREAD

**Issue by urvbcn88** [AdguardTeam/AdguardBrowserExtension#1918]
I don't use the `Do Not Track` feature because websites don't care about the `Do Not Track` signal. Unfortunately, most websites currently ignore the `Do Not Track` signal entirely.

If I turn off `Do Not Track` from AdGuard, the `Global Privacy Control` feature will also be disabled. `Global Privacy Control` is a legal requirement and I want to use it. I found myself in a dilemma here.

My suggestion is that the `Do Not Track` feature should be removed completely or it should work independently of `Global Privacy Control`.

Also, all browsers already include `Do Not Track` feature. So why did you add this to AdGuard?

**Comment by Birbber** [comment]
@urvbcn88 There's no need in getting rid of `Do Not Track`. This feature might still be necessary for those webpages that don't ignore `DNT` as they won't track users, and those that do ignore won't be broken by this feature.
These features were specifically combined in one, since they complement each other.
