### ISSUE TITLE
Redirecting to the wrong page from the link

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#1966]
I'm using AdGuard Beta. It redirects to the wrong page because the phishing and malware protection settings description string has changed from the general settings. The string says "check if domain names are dangerous with our web service" but the link redirects to the AdGuard knowledge base, it should be AdGuard website safety check page. Here's the link: [Website safety check](https://reports.adguard.com/en/welcome.html)

Correct page:
![image](https://user-images.githubusercontent.com/35523759/151727486-e4b738f7-0774-47c2-9e20-813983f5c7ad.png)

Wrong page:
![image](https://user-images.githubusercontent.com/35523759/151727547-dd837ce4-d0ac-44f8-bfac-900020078451.png)

Setting:
![image](https://user-images.githubusercontent.com/35523759/151727223-cde6e437-de88-468b-b39a-d36ad95c6ea6.png)

**Comment by vozersky** [comment]
@gork7777 Hi!  The url is actually correct, it's just the wording that might look a little confusing, we are going to change it a little bit. The point of description is that user should understand that the client will start to exchange domain names hashes with our backend server in order to check if it's safe or not.

**Comment by gork7777** [comment]
Alright I understand, thanks for informing me.
