### ISSUE TITLE
trouble with deactivating Adguard on certain sites

### ISSUE THREAD

**Issue by humphra** [AdguardTeam/AdguardBrowserExtension#2230]
### AdGuard Extension version

4.1.39

### Browser version

firefox 107 for ubuntu

### OS version

kubuntu 20.04

### What filters do you have enabled?

No filters

### Issue Details

the site says that  i have to deactivate the protection of my browser
i have deactivated adguard completely with no change
can you please give me instructions to find out if this is or not a bug ?
i can check if helped
thanks

### Expected Behavior

make it possible to bypass filtering and possibly, easily

### Screenshots

![bug tf1](https://user-images.githubusercontent.com/97979333/202543241-5cb2b5c7-5fbc-4a94-8190-e5e9458982c9.png)

### Additional Information

running firefox 107 on kubuntu 20.04 
everything is updated.

**Comment by contribucious** [comment]
_(**To filters maintainers team:**
Hi. Btw: you may want to check the _Suggestion_ part [here](https://github.com/AdguardTeam/AdguardFilters/issues/133895#issuecomment-1301915301) regarding hardening of request prevention to `static.adsafeprotected.com` for `tf1.fr` and `tf1info.fr` cases.)_

**Comment by mozartinio** [comment]
@humphra 
Hello! Have you tried adding a domain to the allowlist? Added domains in the allowlist is not supposed to be filtered. Also can you please show us your devtools console tab when you try to reproduce the issue

**Comment by contribucious** [comment]
@humphra

:wave: Although your request is more generic, regarding your specific example (TF1), this website is known to display this message if they can't access to tracking location `static.adsafeprotected.com/favicon.ico` (in some cases, they use instead `ads.stickyadstv.com`).

#### Therefore, can you:

<details>
<summary>Click to read me …</summary>

1) Try disabling the AdGuard extension itself completely, if not already done?
:arrow_right_hook: _Normally, you should _continue_ to have this message, proving that it's not due to AdGuard._

2) Try disabling the Firefox built-in `Enhanced Tracking Protection (ETP)` on this particular website?
![2022-11-30_19-47](https://user-images.githubusercontent.com/4764956/204883008-d4e5a4b3-a36b-4252-ba74-a27dedd0c35e.png)
:arrow_right_hook: _Does this help fix the problem? If not, try step 3._

3) Try disabling other locations where this domain name can be blocked? Know ones: AdGuard DNS, AdGuard Home with `AdGuard DNS filter` used; i.e. try another DNS like Cloudflare or Google one, for example.
&nbsp;
</details>

**Note:** However, what AdGuard can do is to do everything possible to circumvent this (request prevention technique) when you enable it (as already currently done although could be improved), but this is not the subject of your general request.

**Comment by contribucious** [comment]
### UPDATE :heavy_check_mark:

The problem was indeed on the Firefox ETP side:


> 107.0.1 — Firefox Release — November 29, 2022

> Fixed an issue with accessing some sites reliably in Private Browsing mode or Strict ETP due to anti-adblockers ([bug 1717806](https://bugzilla.mozilla.org/show_bug.cgi?id=1717806)).

:arrow_right_hook: _Bug 1717806 is `Video does not play at tf1.fr with ETP set to STRICT`. :wink:_

<h5>Can reproduce the bug on <code>107.0</code> and can't anymore on <code>107.0.1</code>.<br>
Therefore, please try beforehand to update to Firefox <code>107.0.1</code>, test again and report here, @humphra. :thumbsup:</h5>

**Comment by mozartinio** [comment]
@humphra Any updates?

**Comment by humphra** [comment]
Hello Maxim
Nothing new : I've finally used an other browser (opera) and anyways tf1 is 'ot my main concern...
Nevertheless I really appreciate your implication for helping. I know a little better adguard after thisthanks a lot have a nice day

Le 5 décembre 2022 09:42:25 GMT+01:00, Maxim ***@***.***> a écrit :
>@humphra Any updates?
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2230#issuecomment-1336963171
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- Sent from /e/ Mail.
