### ISSUE TITLE
Turn caching off for requests downloading filter updates

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#235]
There's an issue with Safari extension. For some reason it caches "getfilter" response and reuses it.

We should turn caching off for backend requests. Pragma no-cache?

Forum issue:
https://forum.adguard.com/index.php?threads/filter-update-bug.9729/

**Comment by Temptin** [comment]
To support good caching to save your bandwidth, you first need to remove all "?" query parameters in the getfilter.html URL. It can be done with URL rewriting rules for things like Apache. The HTTP specification says not to cache URLs with query parameters.

Then you can enable "live forever" caching on /getfilter/'s path via a htaccess rule. So that every request is served via the browser cache if possible.

Lastly, you need a way to deliver new versions of the filter... and the way to do that is to have some reliable token or version number in the URL somewhere. This is an example:

http://mobile.adtidy.org/api/1.0/getfilter/key/4DDBE80A3DA94D819A00523252FB6380/filter/1_1.0.33.38.txt

"1_1.0.33.38" means it would ask for v1.0.33.38 of filter number 1.

How you get the version number to the user, and guarantee that the server returns the version the browser asked for, is up to you. Those are the downsides of caching and need to be solved somehow. I know that you don't keep old versions of the lists, so there's no need for anything but a quick "are they asking for the latest version?" check, and if not, correct it for them Here is one possible solution. Let's say the user asks for v1.0.33.38 above, but the latest is actually 1.4. The getfilter script could then reply with JSON: {"status":"Outdated List Request","latest":"v1.4.0.0"}. Then the client just asks for v1.4.0.0 instead, and gets the right file.

Both requests are now cached:
http://mobile.adtidy.org/api/1.0/getfilter/key/4DDBE80A3DA94D819A00523252FB6380/filter/1_1.0.33.38.txt
http://mobile.adtidy.org/api/1.0/getfilter/key/4DDBE80A3DA94D819A00523252FB6380/filter/1_1.4.0.0.txt

Those URLs will never bother you again from that user since both are cached perfectly and correspond to the version that each URL has delivered.

**Comment by ameshkov** [comment]
> To support good caching to save your bandwidth, you first need to remove all "?" query parameters in the getfilter.html URL

The thing is that we don't want these URLs to be cached.

AG makes these requests only when it is sure that there is an updated filter list.

If you take a look at AG extension network activity, you'll see that it first sends /checkfiltersupdates.html request:
https://chrome.adtidy.org/checkfilterversions.html?filterid=2&filterid=3&filterid=4&filterid=1&app=ag&v=2.2.4&key=4DDBE80A3DA94D819A00523252FB6380
