### ISSUE TITLE
Hiding styles don't work after updating filters

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2447]
### AdGuard Extension version

AdGuard 4.2

### Browser version

Chrome 116

### OS version

Windows 11

### Issue Details

STR:

1. Open https://www.gismeteo.ru/ in incognito
2. Block the element from the screenshot (large window with information about the weather in the city).
3. Reload to the page
4. Open the popup and click on Refresh button to update filters.

For some reason, the blocked element will start displaying again.

### Screenshots

<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/660d8588-6971-4b62-819a-e16d54469703)

</details>

**Comment by slavaleleka** [comment]
It happens because of the Assistant which is launched when you press "Block ads on this website".
The Assistant's way to select a page element is not very efficient — often an element selector is based on the element's position on the page which can change

That's exactly what happens here — not an extension issue, just a bad selector created automatically by the Assistant
