### ISSUE TITLE
'Check for filter updates' option breaks user rules on the current page until you refresh it

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2684]
### AdGuard Extension version

4.2.241

### Browser version

Chrome 121

### OS version

Windows 11

### Issue Details

STR:
1. Go to example.org
2. Click 'Block ads on this website' in the popup menu
3. Block any element on the page and make sure the rule is in 'User rules' section
4. Right click on the page and choose 'AdGuard AdBlocker' > 'Check for filter updates'

### Expected Behavior

User rules should work correctly after checking for filter updates and the blocked element shouldn't be displayed.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by 105th** [comment]
@alexx7311 

**why does this happen?**
When we rely on the `nth-child` selector in the rules, and they count ancestors at the very top level (right after the body, like the header in the picture, which is hidden by the rule `gismeteo.com##header.header.js-header:nth-child(5)`), such rules will break when we inject our iframe with information about filter updates (or version updates) because it is injected at the very first place, in the [`afterbegin`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement#visualization_of_position_names) position.

In theory, we could change it to `beforeend`, so it doesn't disrupt the operation of such `nth-child` rules. On the other hand, it seems that there are extremely few such rules counting descendants from the root element in our filters (except for auto-generated rules through the browser assistant). And changing the position to put it at the very end might, in my opinion, provoke more problematic issues, so we won't be making changes right now.

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/11395678/85e8f958-0dfa-49b0-be68-ec9dc957d57a)
