### ISSUE TITLE
Enabling/Disabling Filter list cause memory bloat, extension lag & rarely crashes.

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardBrowserExtension#2686]
### AdGuard Extension version

v4.3.1 Beta

### Browser version

Chrome v120.0.6099.217 (Official Build) (64-bit)

### OS version

Windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Disabled

### Issue Details

I noticed this on the [AdGuard Filters issues](https://github.com/AdguardTeam/AdguardFilters/issues) by enabling filter list in issues. (Because in some issues, there are those report users enable all in the language-specific filter list.) 😄 Please Check the video.

### Expected Behavior

There should be no lag/memory bloat when enabling the filters.

### Video

<details><summary>Video</summary>

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/56846906/6f330916-98b7-4a18-95c0-b74caa965f05

</details>

### Additional Information

For ease of solution, the examples following issues should be considered:

- https://github.com/AdguardTeam/ReportsWebApp/issues/310
- https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1441

**Comment by alexx7311** [comment]
@kodiakhub Hello! When you click on a switch, the engine is reinitialized and all enabled filters are loaded into it, and then the indexing process proceeds. If you click the switches in the interval from 1 to 5-6 seconds, there will be several engines in memory, and only the browser can delete unnecessary instances because of the limitations of the software platform.

This is the expected behavior of the extension at this point.
