### ISSUE TITLE
Extension settings reset every time I open the browser

### ISSUE THREAD

**Issue by jslawler-gh** [AdguardTeam/AdguardBrowserExtension#2764]
### AdGuard Extension version

Version 4.3.31

### Browser version

Microsoft Edge for Business Version 121.0.2277.83 (Official build) (64-bit)

### OS version

Windows 11 Enterprise 22621.3155

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Every time I open my browser from closed I get the following issues:
1. My AdGuard Browser Extension settings are reset to default
2. The page [filter-download.html](extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/filter-download.html) opens, stating "Please wait while filters database is loading...", and
3. There is no graph on the browser extension showing statistics.

### Expected Behavior

1. Settings are retained on close of browser
2. No page pops up telling me the filter database is loading
3. The statistics graph shows

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/149243371/a2b46436-4a6e-4ae8-af95-c31f8957d556)

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/149243371/777082b7-5324-45f5-9797-46e8679449d9)

</details>

### Additional Information

This is a fresh install.
The issue happens in both private and non-private browsing.
I have tried reinstalling the extension.

**Comment by maximtop** [comment]
Hi! Thank you for reporting this issue to us.

We're currently aware of a bug where the extension may encounter problems if it can't access the filters during installation, due to a lack of internet connectivity. Could it be possible that you're installing the extension without an active internet connection? Could you please check if there are any errors on the background page? Here is a guide on how to do that: [How to export logs from the background page in the extension](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929?pvs=4).

Additionally, you mentioned that your settings reset to default. This can sometimes occur if there are any storage cleaners or similar utilities running on your system. These tools can inadvertently clear the extension's saved settings. Could this be happening in your case?

**Comment by maximtop** [comment]
An error in the log indicates that fetching the URL returns a 403 error. Can you try opening this URL directly in the address bar?

https://filters.adtidy.org/extension/edge/filters_i18n.js?v=4.3.35&cid=PlzJs6Od42492980&lang=en-GB&id=gfggjaccafhcbfogfkogggoepomehbjl

**Comment by maximtop** [comment]
If getting around your company's firewall isn't an option, here are three approaches you could consider:

1. Wait until we sort out a bug that's messing with downloading rules from the packed filters. Once we've got that fixed and rolled out an update, your filters will then only get updated with new builds of the extension.
2. Try cloning the filters to a location that's not blocked by your company's policy. After that, you can add them to the extension as custom filters.
3. Consider building the extension yourself, using a custom URL for the filters.

**Comment by alexx7311** [comment]
Closing as a dup. of #2744
