### ISSUE TITLE
[Critical] Opera 109: This extension may have been corrupted

### ISSUE THREAD

**Issue by lagun** [AdguardTeam/AdguardBrowserExtension#2765]
**The original issue text was changed by AdGuard. We'll be keeping it up to date.**

What we know so far:

1. After publishing version 4.3.31, Opera 109 fails to run it with the error `This extension may have been corrupted`
2. The issue must have something to do with Opera Add-ons.
3. AdGuard team tries to contact Opera asap about the issue.
4. The extension works okay in Opera 108, the issue occurs with Opera 109 only.
5. If you copy the extension from Opera Add-ons and install it as unpacked extension everything will work okay.
6. [Opera logs suggest](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2765#issuecomment-2023390611) that the browser fails to download extension's checksum from Opera Add-ons server.

At this point we think the problem is with Opera Add-ons, waiting for new information from them.

### Temporary solution
Install AdGuard from Chrome WebStore.

**Comment by ameshkov** [comment]
It seems that Opera Add-ons corrupted the extension build, the manifest is different.

The problem is with this line (`<all_urls>` is corrupted):

"permissions": [ "tabs", "\u003Call_urls>", "webRequest", "webRequestBlocking", "webNavigation", "storage", "unlimitedStorage", "contextMenus", "cookies" ],

We're trying to contact Opera asap.

**Comment by maximtop** [comment]
Additionally, I'd like to mention that the extension installed from the Chrome Web Store is working as expected. Similarly, the extension in Opera v108 is also functioning properly.

**Comment by ameshkov** [comment]
We've updated the issue text and explained the current situation.

We'll be keeping the issue text up-to-date and continue our attempts to contact Opera.

**Comment by maximtop** [comment]
According to the logs from Opera, it seems that the extension can't be verified because it's unable to download the verified_contents.json file. 
Here are the relevant log entries:
```
[81718:41987:0327/192351.956435:VERBOSE1:content_hash_fetcher.cc(43)] URLFetchComplete for bopfaehpakahokaelnomggbohfbimcia is_success:0 https://addons.opera.com/extensions/api/content-verification/1.0/signed-contents/bopfaehpakahokaelnomggbohfbimcia/4.3.31/
[81718:41987:0327/192351.956505:ERROR:content_hash.cc(255)] Fetching verified_contents.json for extension id: bopfaehpakahokaelnomggbohfbimcia version: 4.3.31 failed with error code 404
```

**Comment by r4fek** [comment]
We will look into this, thanks for reporting.

**Comment by ameshkov** [comment]
@r4fek thank you!

Just in case maybe this is useful info, I suppose the root cause is this URL:

v4.3.31, 404 Not Found:
https://addons.opera.com/extensions/api/content-verification/1.0/signed-contents/bopfaehpakahokaelnomggbohfbimcia/4.3.31/

Previous version, v4.3.14, 200 OK:
https://addons.opera.com/extensions/api/content-verification/1.0/signed-contents/bopfaehpakahokaelnomggbohfbimcia/4.3.14/

**Comment by avl7771** [comment]
@ameshkov @lagun Thank you for the report. Some important context for the impact: Opera 109 is a beta version, and the number of users using it is many times less than for our stable version. If the bug isn't visible in Opera 108, it means the grand majority of users (>99%) hopefully don't get to see the problem.

We'll make sure Opera 109 doesn't go stable before the issue is solved.

**Comment by ameshkov** [comment]
@avl7771 hmm, it seems to be stable on macOS already, at least this is what I got when installed Opera from the website.

**Comment by avl7771** [comment]
@ameshkov you're right, sorry, it was released but not sent as an automatic update yet - that means that new users get it and existing users if they explicitly update, so definitely more users, but still no big numbers.

Can you confirm you can see the problem on this version, 109.0.5097.33?

**Comment by ameshkov** [comment]
@avl7771 got it, thank you!

> Can you confirm you can see the problem on this version, 109.0.5097.33?

Yes, I can.

Looks like this:

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/5947035/8e62e2b8-7730-450a-986b-38e6d6d56b3a)

Clicking "Repair" does not help.

In the browser logs we see that it cannot download https://addons.opera.com/extensions/api/content-verification/1.0/signed-contents/bopfaehpakahokaelnomggbohfbimcia/4.3.31/

```
[81718:41987:0327/192351.956435:VERBOSE1:content_hash_fetcher.cc(43)] URLFetchComplete for bopfaehpakahokaelnomggbohfbimcia is_success:0 https://addons.opera.com/extensions/api/content-verification/1.0/signed-contents/bopfaehpakahokaelnomggbohfbimcia/4.3.31/
[81718:41987:0327/192351.956505:ERROR:content_hash.cc(255)] Fetching verified_contents.json for extension id: bopfaehpakahokaelnomggbohfbimcia version: 4.3.31 failed with error code 404
```

**Comment by ameshkov** [comment]
Yay, updating to v4.3.35 helped 🎉 

This update was not released according to the schedule, but the main thing is it helped :)

**Comment by ameshkov** [comment]
@avl7771 @r4fek thank you for helping with this so fast!

**Comment by avl7771** [comment]
No problem, thanks for the quick report!
