### ISSUE TITLE
Page refresh delay after disabling/enabling Adguard on page

### ISSUE THREAD

**Issue by alije123** [AdguardTeam/AdguardBrowserExtension#2785]
### AdGuard Extension version

4.3.46

### Browser version

Chromium 122, Chromium 118, Firefox 124.0.2

### OS version

WIndows 10 20h2

### What filters do you have enabled?

No filters, AdGuard Base filter, AdGuard Russian filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Fanboy's Annoyances, Fanboy's Social Blocking List, RU AdList - Counters, Fanboy's Enhanced Tracking List, Fanboy's Anti-Facebook List, I don't care about cookies, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Hide Referrer from third parties

### Issue Details

More filters  => longer delay

### Expected Behavior

Refresh right after disable/enable or show refresh button as ublock

### Screenshots

![issue gif](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/33022255/27189885-f623-4b47-9ab0-759cf4939cd2)

**Comment by alexx7311** [comment]
@alije123 Hello! The delay is due to the fact that the page refresh happens after the extension engine restarts, which usually takes 5-6 seconds. We are still working on optimization and we may be able to reduce this time.

The refresh button won't help, because you still have to wait for the engine to restart.

**Comment by Windrider6** [comment]
I would like to know if/when this issue will improve.  My computers are fast (quadcore, 3.2 GHz), with lots of memory (24 GB), Windows 10 64 bit, installed on SSDs, yet I just counted out 16 seconds on the clock for Adguard to reload a page (latest version of Adguard on the latest version of Firefox).

"Closing" the issue here is not the same as resolving it.
