### ISSUE TITLE
Extension injects scripts every time the extension's background event page wakes up

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2792]
### AdGuard Extension version

4.3.46

### Browser version

Firefox 124

### OS version

Windows 11

### Issue Details

STR:
1) Add `example.com#%#//scriptlet("log", "hello")` to user rules
2) Open a new tab and open the console in it
3) Go to [example.com](http://example.com/) in this tab
4) Minimize your browser's window for a few minutes

You will see in the console that the rule has executed several times.

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/1fa7cbe6-e06d-4930-854b-1d67074a3902)

</details>

### Expected Behavior

The rule should be executed only once.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Revertron** [comment]
Maybe this bug is responsible for HUGE memory leak in all idle tabs.

Just open some websites and leave the browser for some hours, then go to `about:performance` and see that every page uses 250-500Mb of RAM. And if you refresh any page it's usage spikes for x1.5, and then slowly goes to normal, way less than it had before refresh.

This is the behavior of `4.3.46` in `Firefox 126`.
