### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zonde71** [AdguardTeam/AdguardBrowserExtension#2820]
1) After installing ADguard, Firefox starts consuming an infinite amount of memory. Even in idle.
2) It is constantly writing to various files in the directory:
C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\xxx.default-1716219655155\storage\default.
- see screenshot.
Restarting Firefox temporarily solves the problem.
Uninstalling ADguard completely solves the problem.

*Latest version of Firefox 126.0 64bit
*Latest version of Adguard - 4.3.46
TSWebExtension v1.0.22
TSUrlFilter v2.2.18
Scriptlets v1.10.25
ExtendedCss v2.0.56

Sample webpages that was used to monitor an issue:
https://3dnews.ru/
https://www.youtube.com/
https://www.fandom.com/
![adguard1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/170753471/3d09129c-26c9-4166-bf84-1b4aa8e84c70)

**Comment by alexx7311** [comment]
@zonde71 Hello! Is the problem still relevant? Maybe the problem is related to a [Firefox bug](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775) that prevents the extension settings from being saved.

Have you noticed that the settings in the extension are reset?
Have you changed the default browser settings? How many tabs do you have open? The more information the better.

**Comment by zonde71** [comment]
Hello,
The problem is still relevant.
This is not related to the problem that prevents you from saving extension settings.

Windows 10 Pro 22H2; Firefox 126.0.1 64bit; 
Adguard -  4.3.53
TSWebExtension v1.0.24
TSUrlFilter v2.2.18
Scriptlets v1.10.25
ExtendedCss v2.0.56

I open the browser with only 2 tabs:
1) https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2820
2) -new empty tab
Then open tab-N3) https://3dnews.ru/
Then open another empty tab
Then minimize the browser.

After these steps we can observe memory consumption growth of Firefox process. About ~100-200MB per hour not even touchig the brouser (keeping it minimized with the last empty tab open)

**Comment by dewhisna** [comment]
I'm also seeing what appears to be this same memory leak issue on multiple computers running Linux on varying Ubuntu distros -- specifically Bionic, Focal, and Jammy.
Firefox 128.0 (such as 128.0+build2-0ubuntu0.20.04.1)
AdGuard 4.3.64

On some of the computers that only have 16GB or so of RAM, I only have one or two tabs open and if I leave it running for a couple of days to a week (not even using the computer during that time), I will return to find the disk drive thrashing and it bouncing off of swap memory until I kill Firefox.  On this PC, while I do have an insane number of windows and tabs open, it hasn't been an issue until recently even with the same exact windows and tabs.  This machine has 128GB of RAM and if I leave it overnight, it will be almost at swap space by the morning.  So the leak seems to be proportional to window/tab count.

I found that simply going into the add-ons page and disabling this plugin will keep it from continually climbing and prevent it from running the computer out of RAM and seemingly free the memory that it was consuming, which is why I don't think it's Firefox itself.

This all started about a year or so ago on several of my computers, initially on the computer running Jammy and then later on a computer still running Bionic, but I didn't have time to narrow it down then and simply exited Firefox on those machines to keep it from running away.  This specific computer I'm on now (which is the one with 128GB of RAM and is running Focal), just recently started exhibiting the same problem.

Since I use this computer more than the others, I started trying to narrow it down and is when I found that if I disable this plugin, the memory leak seemed to stop.  So I searched for other reported cases to see if others were experiencing it and arrived at this issue.

It also doesn't seem to be related to it being a system Firefox package or a Snap package, as the Bionic and Focal machines are system packages, but the Jammy machine where I first started encountering problems, is a Snap package of Firefox.

**Comment by alexx7311** [comment]
@zonde71 @dewhisna Does the problem reproduce on the latest 4.4.22 version?

**Comment by dewhisna** [comment]
@alexx7311 -- yes, it seems to still be present on 4.4.22.  If anything, possibly a little worse? (or at least the same).  On my PC with 128GB of RAM, I hit a wrong button the other day that closed my many hundreds of tabs and windows that were previously open and deleted the entire cache and history.  I'm back to a single window with about a dozen tabs.  I restarted Firefox about ten hours ago, and in these ten hours or so, memory usage has already crawled back to about 50%.  Looking at memory usage via tools like `top` and `ps` confirms it's being consumed by Firefox.

If I disable the plugin, it doesn't immediately free the extra RAM, but it stops climbing and gradually starts giving some back, as if there's a garbage collector running.  If I leave it long enough in that state, it will return back to the same memory usage as when I initially launched Firefox

**Comment by zonde71** [comment]
Nothing changed with latest 4.4.22 version.

**Comment by Tasiorsa** [comment]
> @zonde71 @dewhisna Does the problem reproduce on the latest 4.4.22 version?
Windows 11 Pro
Firefox 130.0
Adguard 4.4.22 - fresh install
Still the same issue - screen after 10 hours - 8 bookmarks
![365359154-56afa858-855e-42d8-92f7-bf8f0fdab533](https://github.com/user-attachments/assets/9486ffb8-5a9b-4996-9ccf-f9bc4beea2c3)
