### ISSUE TITLE
[Q] Adguard extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions

### ISSUE THREAD

**Issue by SM-03** [AdguardTeam/AdguardBrowserExtension#2886]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

For the last couple of days, I have been receiving this notification under the chrome://extensions/

> These extensions may soon no longer be supported
Remove or replace them with similar extensions from the [Chrome Web Store](https://chromewebstore.google.com/category/extensions)

Screenshot [here](https://zupimages.net/up/24/31/kzjt.png): 

Then I visited the official Adguard Browser Extension [here](https://chromewebstore.google.com/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg)

and in there also shows this message

> This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

-Screenshot [Here](https://zupimages.net/up/24/31/bdz8.png)

So asking it here? Why this? Someone care to explain?

**Comment by alexx7311** [comment]
@SM-03 Hello! This notification is due to the fact that Chrome will soon [stop supporting MV2 extensions](https://adguard.com/en/blog/adguard-mv3.html) and will phase them out. 
But we already have a [beta version of MV3 extension](https://adguard.com/en/blog/adguard-mv3-beta.html), which can be found at https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v5.0.5-beta

When the 5.0 (MV3) extension release comes out, it will replace the current version of the extension (MV2) and if possible all your saved settings will be migrated.

We will continue to support the 4.0 version (MV2) as much as we can, but only MV3 extensions will be allowed in Chrome.

**Comment by SM-03** [comment]
@alexx7311 
Thanks for the clarification, 

so this new beta MV3 v5.x version will replace the existing MV2 v4.x automatically for the unaware users when it will finally released & out for the beta phase?

or user has to uninstall v4.x (MV2) by themselves & install the new v5.x (MV3) manually? 

Also, is there any ETA for the public release of this beta v5.x?

**Comment by alexx7311** [comment]
@SM-03 
> so this new beta MV3 v5.x version will replace the existing MV2 v4.x automatically for the unaware users when it will finally released & out for the beta phase?
> 
> or user has to uninstall v4.x (MV2) by themselves & install the new v5.x (MV3) manually?

While we have time, we'll first release the 4.4 version of the extension and continue to release beta versions of 5.x, adding new functionality and fixing issues. 

Eventually, the 5.x release build will replace the 4.x version from the Chrome Web Store [here](https://chromewebstore.google.com/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg).

You won't have to install anything again, the update will take place automatically.

> Also, is there any ETA for the public release of this beta v5.x?

It's up to the Chrome developers, but we'd like to release 5.x as late as possible.
