### ISSUE TITLE
Prevent videos from playing automatically

### ISSUE THREAD

**Issue by mehdifirefox** [AdguardTeam/AdguardBrowserExtension#2974]
### Issue Details

I don't know if this is a bug or a request for a new feature
Because I think you should have added this important item by now 

Advertising videos are played automatically
Like the site theregister.com 

### Proposed solution

n/a

### Alternative solution

👍

**Comment by alexx7311** [comment]
@mehdifirefox, hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

**Comment by mehdifirefox** [comment]
> @mehdifirefox, hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

I reported the problem here, it was much faster than trying to do it directly through the plugin
Why are there so many steps? Mandatory screenshot

In this way, the user stops reporting

Reporting should be one click

**Comment by alexx7311** [comment]
@mehdifirefox Issues related to filtering, rather than the extension itself, are handled by our Filters team. This repo is for the extension-related problems and features.

It's not robots that handle these things, it's people. You need to go to the website, understand the problem and find a solution. Sometimes it is impossible to understand the problem without a screenshot and requesting screenshots every time is a waste of time for both the user and the Filters team, so screenshots are mandatory. If you look in the Filters repository at https://github.com/AdguardTeam/AdguardFilters/issues, you will find several hundreds of open problems that need to be solved and it is not very productive to write to each user separately with a request to attach a screenshot.

If you were creating a task in the right repository, you would have to fill in all these fields from https://github.com/AdguardTeam/AdguardFilters/issues/new?assignees=&labels=Unsorted&projects=&template=bug_report.yml

But the report tool I sent you to solves most of the problems, as the extension itself will fill in most of the fields for you.

**Comment by mehdifirefox** [comment]
> @mehdifirefox مسائل مربوط به فیلتر کردن، به جای خود برنامه افزودنی، توسط تیم فیلترهای ما رسیدگی می شود. این مخزن برای مشکلات و ویژگی های مربوط به برنامه افزودنی است.
> 
> این ربات ها نیستند که این چیزها را اداره می کنند، بلکه مردم هستند. شما باید به وب سایت بروید، مشکل را درک کنید و راه حلی پیدا کنید. گاهی اوقات درک مشکل بدون اسکرین شات غیرممکن است و درخواست هر بار اسکرین شات برای کاربر و تیم فیلترها اتلاف وقت است، بنابراین گرفتن اسکرین شات اجباری است. اگر به مخزن فیلترها در [ https://github.com/AdguardTeam/AdguardFilters/issues ](https://github.com/AdguardTeam/AdguardFilters/issues) نگاه کنید ، صدها مشکل باز پیدا خواهید کرد که باید حل شوند و نوشتن برای هر کاربر به طور جداگانه با یک درخواست کار چندان مفیدی نیست. برای پیوست کردن اسکرین شات
> 
> اگر یک کار را در مخزن درست ایجاد می کردید، باید همه این فیلدها را از [ https://github.com/AdguardTeam/AdguardFilters/issues/new?assignees=&labels=Unsorted&projects=&template=bug_report.yml پر کنید. ](https://github.com/AdguardTeam/AdguardFilters/issues/new?assignees=&labels=Unsorted&projects=&template=bug_report.yml)
> 
> اما ابزار گزارشی که برای شما فرستادم اکثر مشکلات را حل می کند، زیرا خود افزونه بیشتر فیلدها را برای شما پر می کند.

I have no business giving you system specs.

I still say that there are many long steps
Send my suggestion to the product manager

1.I agree to send you my system log
2. Explanation box about the problem 

As simple as that

I say that the video opens automatically on this site
Why should I send a screenshot?
What should I send from?
