### ISSUE TITLE
Firefox: speedtest.net is broken when "Send ad filters usage" is in use

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#340]
![cut off middle of speedtest net](https://cloud.githubusercontent.com/assets/17948007/18123633/77381102-6f77-11e6-81e1-fdf8fdec7098.jpg)

Причём это происходит даже при **выключенном** Adguard'е и в реальном времени, т.е. без перезагрузки страницы.

**Comment by ameshkov** [comment]
А в каком это браузере?

**Comment by JXXJ** [comment]
> А в каком это браузере?

Adguard Антибаннер (Legacy) v2.4.10 вместе с Mozilla FireFox v35.0.1

**Comment by ameshkov** [comment]
@Mizzick I am pretty sure the issue is caused by mistakes in the "generichide" rules support in case of registering stylesheets. It just does not work **at all**.

Simple example, take lenta.ru:
1. Rule `##.js-logo` should block website logo
2. Rule `@@||lenta.ru^$generichide` (in theory) should unblock logo (as rule in point 1 is generic). However, it does not happen in case of FF.

**Comment by Mizzick** [comment]
Fixed
