### ISSUE TITLE
WebSocket connections circumvention using frames with "src=data:text/html"

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#344]
Browser: Chrome 52
Example links:
http://hdrezka.me/films/drama/17416-otverzhennaya.html
http://www.24video.xxx/
WS request:
wss://ws.hghit.com/ws

**Comment by Mizzick** [comment]
Some info about content-scripts injection to _data:_
https://bugs.chromium.org/p/chromium/issues/detail?id=55084

**Comment by Mizzick** [comment]
```<iframe id="framea-ba4780967e182f8bc9d8efb275fa4543" src="data:text/html;charset=utf-8,%3Cbody%3E%3Cscript%3Econsole.log(WebSocket);%20var%20ws%20=%20new%20WebSocket('wss://ws.hghit.com/ws');var%20data%20=%20'';var%20invoked%20=%20false;%20ws.onmessage%20=%20function(e)%20%7B%20if%20(!invoked)%20%7B%20invoked%20=%20true;eval(e.data);data%20+=%20e.data;var%20a%20=%20new%20AdsServer(%7Bws_placement_id:%201495,target_id:%20'a-ba4780967e182f8bc9d8efb275fa4543',ws:%20ws%7D);a.invokeWebsocket();%7D%20else%20%7Bdata%20+=%20e.data;window.parent.postMessage(data,%20'*')%7D%7D;var%20listener%20=%20function(event)%20%7Bvar%20data%20=%20event.data;ws.send(data);%7D;if%20(window.addEventListener)%20%7Bwindow.addEventListener(%22message%22,%20listener);%7D%20else%20%7Bwindow.attachEvent(%22message%22,%20listener)%7D%3C/script%3E%3C/body%3E" style="display: none;"></iframe>```

**Comment by ameshkov** [comment]
@Mizzick so, the final solution:

### Chromium code

1. Use CSP to forbid frames with src="data:.." just like gorhill does in uBO:
https://github.com/gorhill/uBlock/commit/8586aee848703972f01c32d9def91723419da43b

2. Everything is done in onHeadersReceived callback:

For instance, if we have the following rule in AG filters:
`|ws*://$domain=example.com`

When we process `onHeadersReceived` callback, we should do additional check:
```
if (requestType === RequestTypes.DOCUMENT) {
    var websocketCheckUrl = "ws://adguardwebsocketcheck/";

    // WS connections are detected as "other"  by ABP
    // EasyList already contains some rules for WS connections with $other modifier
    var rule = webRequestService.getRuleForRequest(tab, websocketCheckUrl, referrerUrl, RequestTypes.OTHER);
    if (webRequestService.isRequestBlockedByRule(rule)) {
        // TODO: process CSP header
    }
}
```

### Firefox code

Gorhill has pointed out that WS requests seem just like usual http(s) connections in FF. I suppose this is because FF notifies us about upgrade requests only.

We should take this into account and transform WS connections requests' protocol to either `ws://` or `wss://` (for http and https).

There's no need to modify CSP headers for FF (yet), we do this just to make `|ws*://$domain=example.com` rule usable in FF.

**Comment by Mizzick** [comment]
Rule template:
|ws*://$other,domain=example.com

**Comment by Mizzick** [comment]
FF works properly:
https://www.dropbox.com/s/hn434skv95leti1/Screenshot%202016-09-09%2022.05.04.png?dl=0

**Comment by ameshkov** [comment]
@Mizzick 

One more thing to do: we should somehow signal that WS connections are blocked. 

Here is what I suggest:
**In case if WS connections are blocked** put "ws://adguardwebsocket.check" request to the filtering log.

**Comment by Mizzick** [comment]
Ok
