### ISSUE TITLE
False alert on http://diep.io/

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#349]
http://i.imgur.com/GDQdfOC.png

The issue is there even when ad blocking is turned off for that website.

**Comment by Mizzick** [comment]
We can make websockets exceptions list somehow.

**Comment by Mizzick** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/346

**Comment by ameshkov** [comment]
I suggest trying another solution before hardcoding an exceptions list. 

Let's try using the same way as ABP for WebSocket wrapping:
https://github.com/adblockplus/adblockpluschrome/commit/457a336ee55a433217c3ffe5d363e5c6980f26f4

**Comment by Matheus28** [comment]
Hi,

I'm the developer of diep.io. The problem is that we check the prototype of a lot of objects to make sure nothing has been modified, because some people were writing browser extensions that would give an unfair advantage to the user.

The best solution would be only overriding the constructor, and checking the constructor params to decide whether to filter or not (copy the prototype from the real WebSocket, like ABP does).

**Comment by Mizzick** [comment]
Ok, done.
Thanks @Matheus28
