### ISSUE TITLE
tvcast.naver.com

### ISSUE THREAD

**Issue by SlowMemory** [AdguardTeam/AdguardBrowserExtension#408]
I'd like to report a problem posed in this issue https://github.com/SlowMemory/List-KR/issues/60.
Steps to reproduce:
- In the chrome browser extension, disable every filters and add following two rules to the user filter.

```
||smartmediarep.com/*.mp4|
||damovie.dn.naver.com^
```

   as these are sources of almost all preroll ads.
- Go to http://tvcast.naver.com/v/1181483 , or any other vods in tvcast.naver.com.
- Sometimes no preroll video ads will be played, but if they were loaded and blocked by above rules, an inline style attribute `display:none!important;` is included in the video element (search for "video[id^="rmcPlayer_"]"), so the image is hidden and only the sound plays.

I tried similar things (disabling every other filters/modules and enabling only 2 rules) with other adblocking tools: `display:none!important` was added for ABP too, but not for Adguard for Windows and ublock origin.

Can you take a look at this and give filter rules or update the chrome extension so that I can properly block preroll ads? Can the way Adguard extension blocks requests be the cause? I thought javascript injection, the use of shadow dom, or the websocket wrapper might be conflicting with their video player, but it seems not to be the case.

**Comment by ameshkov** [comment]
In my case the video simply does not work due to javascript errors. With or without Adguard, it does not matter. So I can't yet provide you with a temporary solution.

However, I think I know what's the reason.

I suppose they use the same `<video>` element for pre-rolls and legit video.

So here is what happens:
1. They put an ad URL to the `src` attribute.
2. Ad request is blocked by Adguard.
3. This is detected by the content script and video tag is "collapsed" (display: none style).
4. Then they change `src` attribute value to a legit video URL.
5. However, the element stays collapsed.

**What should we do in order to fix it:**
1. We should keep track of collapsed elements.
2. When `load` event is triggered, we should check if this element was previously collapsed. If it was, we should unhide it.

**Comment by ameshkov** [comment]
**Here is another way**
Instead of adding style: display none for collapsed elements, we could add a style:
```
TAG_NAME[src="blocked url"]
```

Thus we won't need to keep tracked of collapsed elements src attributes.

**Comment by ameshkov** [comment]
Actually, I like the second approach more.

But here is one thing about it: we'd better add this new style to the shadow DOM (if it is available).
Slight rework of the domcollapser is required.

**Comment by Mizzick** [comment]
I'm not sure this is a good idea to change the shadowDOM on the fly, or I didn't get you?

**Comment by Mizzick** [comment]
Okay

**Comment by ameshkov** [comment]
@Mizzick suggested implementation is not acceptable, you should rethink it.

**Comment by Mizzick** [comment]
Should be fixed, but Im not able to try any video on this site.

**Comment by ameshkov** [comment]
Let's close it then, it should be definitely fixed.

**Comment by ameshkov** [comment]
@Mizzick 
Now it adds a selector for hiding a legit video.

We should use `src` attribute value which was sent to the background page and not the one it has now.

**Comment by SlowMemory** [comment]
Seems to be fixed. Thank you!
