### ISSUE TITLE
Settings are not saved on MS Edge when browser is closed

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#563]
Settings are not saved on MS Edge when browser is closed.

Whenever I close and then re-open the browser, all settings get reseted and all filter subscriptions and user filters as well.

**Comment by atropnikov** [comment]
Hello, @pedrogarcia. Which version of Edge and Windows do you use? I cannot reproduce this issue on my system. Do you see something like that for other extensions?

**Comment by ameshkov** [comment]
Here is the cause of it:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/566

Due to this 5MB limit, choose the filters you use carefully. For instance, don't use English filter along with the EasyList as both filters are huge and might cause the overflow. English filter is the EasyList fork, so you can stick with it.

I hope we'll be able to fix the issue in the next extension update as Edge seems to support `unlimitedStorage` permission now.
