### ISSUE TITLE
Filter list removal request

### ISSUE THREAD

**Issue by jspenguin2017** [AdguardTeam/AdguardBrowserExtension#701]
Hi, I heard that AdBlock Protector List is added to Adguard settings page. Please, remove it, at least until we have announced that we will offer support for Adguard. 
Our filter is not designed for Adguard and we do not have the resource to handle those issues that are opened in our repository. It does not benefit you neither, since we will ask the user to uninstall Adguard, and we have done so several times already. 
If you wish to make a filter that is based on ours, feel free to do so, but please do not send issues to our repository. If you wish, we will be happily list your filter as an alternative on our home page. 
We have kindly asked you to remove the filter, but if it is not removed in 7 days, we will take steps to make sure the filter is unusable on Adguard without modification.

**Comment by ameshkov** [comment]
It's not that we add filter somewhere, there is a repository of known filter subscription and users can find your filter there.

We will mark it as incompatible.

**Comment by ameshkov** [comment]
> but please do not send issues to our repository

Just to make it clear - no Adguard official representative ever send anyone to your repository. Furthermore, we were not recommending people to use Adblock Protector.

People were doing it on their own, looking for a reek's successor.

**Comment by jspenguin2017** [comment]
Our project is NOT a replacement of Reek's work, we have deleted thousands of lines of compatibility checks to speed up our code for one specific setup. Since there is nothing you can do, I will activate our installation check rule.

**Comment by BooBerry** [comment]
It's been marked as incompatible in the available filter subscriptions repo on Adguard for Windows. I've also posted sticky topics on the forums explaining to users that they need to remove the Adblock Protector filter and userscript.

![gac3iep](https://cloud.githubusercontent.com/assets/5448916/26368969/ea207d14-3fb8-11e7-8cb8-e8cf43513d9b.png)

It should probably be fully removed from the list and blocked from manually being added as a filter via its direct URL.

But, it seems the script (which make be broken since it points to the old URL) can still be toggled without any warnings in the Adguard browser extension 2.6.1 beta builds. It should probably be completely removed from that list (and new betas issued) @ameshkov and @vbagirov

**Comment by jspenguin2017** [comment]
@BooBerry 
Why would you guys close and lock the thread before properly solving the issue? 
Bodge, close, lock, forget about it. To me, this is saying that you don't care.

**Comment by BooBerry** [comment]
Which thread? This one? It's open from what I can see, but it looks like it was limited then unlocked (accident?). Also I can't lock/unlock Github threads here.

If you mean the sticky topics on the forums, yeah, I stuck and locked those since I thought the information was pretty clear, and there's already one open topic to discuss it.

**Comment by jspenguin2017** [comment]
@BooBerry GitHub thread cannot be locked by accident. 
![image](https://cloud.githubusercontent.com/assets/7283682/26370232/6870cad4-3fb4-11e7-84f7-bae163e21523.png)

**Comment by BooBerry** [comment]
Again, that's for @ameshkov

I'm guessing since it was marked as incompatible via the subscriptions list, the issue was 'resolved' and thus closed - not sure the 'limited' and 'unlocked' parts. Though, personally, I think it should be fully removed from the subscriptions list completely.

**Comment by jspenguin2017** [comment]
@BooBerry That's correct, the issue was not solved to my expectation before being closed, thus, I taken step myself to motivate developers to properly solve this issue.

**Comment by BooBerry** [comment]
Completely removing it from the subscriptions list might require a new Adguard for Windows beta build, along with new beta builds for the Adguard Adblocker browser extensions (IMO, the subscriptions list should be maintained/updated outside of those so issues like this, in addition to adding new filter lists, removing dead/discontinued/incompatible filter lists, etc. can be handled without needing program/extension updates). AFAIK, only the Adguard for Windows 6.2 beta and the Adguard Adblocker 2.6.1 beta browser extensions have this listed as an option via the subscriptions list.

I'm guessing it'd take time regardless to handle this removal, issue new betas, etc.

**Comment by jspenguin2017** [comment]
@BooBerry Then inform me and don't close the issue. 

> It's not that we add filter somewhere, there is a repository of known filter subscription and users can find your filter there.
We will mark it as incompatible. 
ameshkov closed this 11 hours ago
ameshkov locked and limited conversation to collaborators 11 hours ago

This translates to "We can't remove that, we'll mark it as incompatible. Now shut up."

**Comment by ameshkov** [comment]
Hey, guys, it seems I've missed something here. I don't read all the Github notifications, need some time to code:) so don't get mad at me for the late replies.

Let me please explain everything.

1. Known filters list (part of it is in the screenshot above) is just a list of known filter subscriptions. We keep track of every filter subscription so that people could pick a filter from the list instead of installing it by a URL.

2. "Marked as incompatible" means that the filter's metadata was changed so that it was clear that it should not be used with AG. There is no removal procedure for the known filters subscriptions list yet.

    Offtop: Maybe it's time to have it, though. For instance, there're some filters which are no more supported (like norsk or wiltteri).

3. One more time I'd like to emphasize an important thing: there was no promotion of AdBlock Protector in AG or whatever. Guys on the AG forum discovered and tried it, I guess that's why there are some reports from AG users. Overall, there might have been a dozen of people who had it installed.

4. Closing this issue meant that there is nothing more can be done at the moment. There were no implications you are mentioning. 
    
5. @BooBerry is a user and not a developer, there's no need to call him "you guys"
    
6. > Our project is NOT a replacement of Reek's work

    I did not say that your project is a replacement. I merely tried to explain where AG users could have come from.

**Comment by BooBerry** [comment]
> Offtop: Maybe it's time to have it, though. For instance, there're some filters which are no more supported (like norsk or wiltteri).

And AAK itself too, since it's probably dead as a doornail.

> I did not say that your project is a replacement. I merely tried to explain where AG users could have come from.

I'll venture a guess here, people saw the part of it being a fork of (err, powered by) Anti-Adblock Killer, which development slowed down until it was more-or-less dead and saw AP which was being actively developed (which is what I assumed at first glance - I never used AAK or AP). Users began asking about it on the forums, and requested the filter list be added to the known subscriptions list. I've been telling people from day one that wanted to use the filter/script that most of the filters won't even work in Adguard and that it'd be better to report Anti-Adblock websites to the Missed Ads filter.

IMO the AP page is pretty vague, it should mention right from the start that it's for uBlock Origin only.

> @BooBerry is a user and not a developer, there's no need to call him "you guys"

lol yeah, I tried to explain that.

**Comment by jspenguin2017** [comment]
@ameshkov There are many things you can do: 

1. Fork the list and patch it so it runs in Adguard. 

2. Just update the list. No removal procedure? You don't have access to the file? I don't believe it. 

3. Direct all issues about the filter list to your repository. 

I will happily accept any of these as a solution, telling me you can't help and close the issue is not acceptable. 

Please realize that I am the only committer of AdBlock Protector, I assure every new rule that goes into it is properly tested. I want to keep the quality of the project, and I don't have time to test on other setups. 
You guys added the filter list to your settings page and flood my repository with your users asking me to support Adguard, and now you refuse to clean up the mess you caused, I am very disappointed in the way you handled this issue.

**Comment by jspenguin2017** [comment]
@BooBerry 
AdBlock Protector does everything AAK does, and more, but it only works on a single setup. I rewrote 5000 lines of code, re-implement and optimize thousands of solutions for that single setup. 
We believe supporting many setups is the ultimate reason AAK failed, so we do not want to let that happen again.

**Comment by ameshkov** [comment]
@jspenguin2017 

> Just update the list. No removal procedure? You don't have access to the file? I don't believe it.

Yup, never occurred before.

1. There is an index file with all the filters available:
https://filters.adtidy.org/extension/chromium/filters.json
2. Every filter assigned with an ID.
3. When a user picks a filter from the list, this ID is saved to the database and then used for checking all the updates against that index file.

So, the problem is that we didn't test what happens when there is no more filter with the specified ID. The issue is complicated because it should be tested with all AG products (extension/windows/mac/android/ios).

> I will happily accept any of these as a solution, telling me you can't help and close the issue is not acceptable.

I have never told you that I can't help. On the contrary, I suppose that having it marked as incompatible is a better solution than just removing it.

Let me explain why:

1. Removing it won't prevent it from being added from the direct URL.
2. When a user decides to add a filter from a URL, AG first checks the known filters list and gets the filter metadata from there.
3. So, if it is on the list, the user will immediately see that the filter is incompatible.

**Comment by BooBerry** [comment]
> 1. Removing it won't prevent it from being added from the direct URL.
> 2. When a user decides to add a filter from a URL, AG first checks the known filters list and gets the filter metadata from there.
> 3. So, if it is on the list, the user will immediately see that the filter is incompatible.

Huh, you're right, the filter can't be added anymore (nor can it from the URL) and results in an empty filter with a link to this issue. That pretty much resolves the issue, IMO.

**Comment by ameshkov** [comment]
> Huh, you're right, the filter can't be added anymore (nor can it from the URL) and results in an empty filter with a link to this issue. That pretty much resolves the issue, IMO.

Yep, that's what I did from the very beginning (when the issue was closed 13 hours ago).

I guess Steve from the forum had experienced that warning because he had the filter installed by URL long time ago when it was first time mentioned there.

**Comment by BooBerry** [comment]
You can still install the filter using its URL;

`https://raw.githubusercontent.com/jspenguin2017/AdBlockProtector/master/AdBlockProtectorList.txt`

And checking for updates doesn't result in the empty filter with a comment link to this issue. Might want to check that.

**Comment by jspenguin2017** [comment]
@ameshkov 
Thank you, that is a better response. Please also remove any reference to our repository, so we won't be receiving people asking for adding support. 

@BooBerry 
I have clearly marked Adguard as "known to not work" on my home page, that shouldn't be a problem.

**Comment by ameshkov** [comment]
@BooBerry will use `https://github.com/jspenguin2017/AdBlockProtector/raw/master/AdBlockProtectorList.txt` then as it is the one mention on https://jspenguin2017.github.io/AdBlockProtector/

**Comment by BooBerry** [comment]
> I have clearly marked Adguard as "known to not work" on my home page, that shouldn't be a problem.

For those who don't read (you'd be surprised how many people don't - they just look for the install button, ROFL) you might want to make it flash or blink or something like that so they do read it (or another color or something).

> https://github.com/jspenguin2017/AdBlockProtector/raw/master/AdBlockProtectorList.txt then as it is the one mention on https://jspenguin2017.github.io/AdBlockProtector/

So it'll be switched to the new URL and adding the filter via URL won't work anymore? Groovy. That'd solve that part, just gotta inform people on the forums to remove the userscript from Adguard's extensions. 👍

**Comment by ameshkov** [comment]
> Please also remove any reference to our repository

Will be updated in the index file soon (once cached ver is updated)

**Comment by jspenguin2017** [comment]
@BooBerry 
If it becomes a problem, we'll be banning people who don't read.

**Comment by BooBerry** [comment]
> So, the problem is that we didn't test what happens when there is no more filter with the specified ID. The issue is complicated because it should be tested with all AG products (extension/windows/mac/android/ios).

From my own testing only Adguard for Windows 6.2 beta and the Adguard browser extension 2.6.1 betas list AP in the list of filter subscriptions - it hasn't been added to Mac or Android (not sure about iOS).

Once the new URL is in place, and the cached ver is updated, let me know and I can test it in both. :)

**Comment by BooBerry** [comment]
Okay, filters.json has updated to the newer URL and I can't add the filter via this URL:

`https://github.com/jspenguin2017/AdBlockProtector/raw/master/AdBlockProtectorList.txt`

But you still can from this URL;

`https://raw.githubusercontent.com/jspenguin2017/AdBlockProtector/master/AdBlockProtectorList.txt`

As a precaution this one should also be marked as incompatible, since it's not hard to obtain this URL.

**Comment by ameshkov** [comment]
> As a precaution this one should also be marked as incompatible, since it's not hard to obtain this URL on the Github repo page.

Can't have multiple URLs at the moment so it'd be better to have the one that it is more likely to be used.

Summing it up:
1. Filter discover through AG settings is solved due to the clear marker.
2. No link to the repo.
3. Installing by the direct link found on the homepage is impossible.

**Comment by BooBerry** [comment]
@ameshkov it works for the browser extension beta too. But for them, it might just be wise to remove it from the list in the next beta, as it doesn't say the filter/script is incompatible and users may go to @jspenguin2017 on the AP repo and report issues (even though the filter isn't working at all, but they can't view the filters or lack there of in the browser extensions). Also users can't add additional filters via URL so it might be best to remove it completely in the next beta. Since AP hasn't been added to Mac or Android (and you can't add filters via URL there) it's probably best to not add AP in the list there either.

**Comment by jspenguin2017** [comment]
I guess it is still causing confusions, so we have made several changes: 

1. AdBlock Protector is now strictly for Chrome, uBO, and Tampermonkey, opening issues with a different setup will result in a ban (with reasonable warning for now, will be harder and stricter later). 
2. AAK-Cont the "sloppy" version of AdBlock Protector and accepts every possible setups, with exchange of some performance. To overcome difference in ad blocker filter syntax, we have one generic filter with AdBlock / Adblock Plus syntax, and 3 other filters with specific to AdBlock / Adblock Plus (non-ideal white listing, let ads in when there is no other solution), uBlock Origin (for FireFox, etc), and Adguard. 
3. AAK-Cont will accept newbies question in issues tracker, and every part of the project can (is expected to) run alone, we will have duplicate solutions when appropriate (we obviously won't have 4 copies of solutions, by separate I mean one solution can't affect two files). One major problem with AAK-Cont is that it expects community support, as I will not put as much time into it. 

If you wish to replace the current entry of AdBlock Protector with AAK-Cont, that would be great, when there is an alternative, people will stop searching, and we will receive less [garbage](https://github.com/jspenguin2017/AdBlockProtector/pull/235) in AdBlock Protector repository. 

I have linked back to AdBlock Protector in AAK-Cont so people with the right setup can benefit from the optimization.

**Comment by ameshkov** [comment]
@jspenguin2017 
> we will receive less [garbage](https://github.com/jspenguin2017/AdBlockProtector/pull/235) in AdBlock Protector repository

Ok, that's enough, I am tired of your disrespectful behavior.

You do realize that @SMed79 is Liste AR and Liste FR maintainer, right? He is the guy who does support ad blocking for a long time now and did A LOT for everybody, not just for his ego. Of course, how could you know, he is not <a href="https://cloud.githubusercontent.com/assets/5947035/26443439/19a0d14a-4141-11e7-8323-2f4c9cd71138.png" target="_blank">shilling</a> <a href="https://cloud.githubusercontent.com/assets/5947035/26442953/43b1f1dc-413f-11e7-80fb-3bd22e622e95.png" target="_blank">everywhere</a>, telling who and <a href="https://cloud.githubusercontent.com/assets/5947035/26444145/ccd8bd48-4143-11e7-9c99-6fcfb35611b6.png" target="_blank">how important</a> he is.

Also, he is not a mentally unstable (<a href="https://cloud.githubusercontent.com/assets/5947035/26442801/a30ef676-413e-11e7-9856-1a380bdbc468.png" target="_blank">1</a>, <a href="https://cloud.githubusercontent.com/assets/5947035/26442803/a48502c0-413e-11e7-8704-520ddef89d64.png" target="_blank">2</a>, <a href="https://cloud.githubusercontent.com/assets/5947035/26443533/796b0500-4141-11e7-8e46-c70491b96fbe.png" target="_blank">3</a>) guy, who tries to <a href="https://cloud.githubusercontent.com/assets/5947035/26443129/e0dbf516-413f-11e7-9d99-382e6170d050.png" target="_blank">sneak in a JS alert/redirect</a> to common people trying to get revenge for **literally 5 issues opened by 2 people in 2 months** (<a href="https://github.com/jspenguin2017/AdBlockProtector/issues?utf8=%E2%9C%93&q=adguard" target="_blank">search link</a>, note that most of the issues are people mentioning Adguard filters which are often used as rules source).

Let me get this straight, we will not promote or mention anything **maintained by you** and obviously never recommend anybody. This time you decided to sneak in an alert because you were pissed, god knows what will you do next time.

Now get lost.

----
@xxcriticxx, @uBlock-user, @ghajini, hi guys, I know you're helping the guy, so this drama might be interesting to you.

**Comment by ghajini** [comment]
Yep adguard do right amount updating its filters regularly, actually has  enhanced version of easylist and has solutions for antiadblock as script based.....its `NOT` garbage.....

**Comment by jspenguin2017** [comment]
As you don't want to listen anymore, I'll just put this here, lock if you wish. 

First, I don't know who @SMed79 is, he is just another person who missed 3 warnings I put on the homepage, readme itself, and the contribution guideline. Oh, I also have one on the issues template but he opened pull request so I won't count that one. He clearly didn't ready anything about the project and thought "huh, this phrase doesn't sound right, let's change it". If he even opened the contribution guideline, he would immediately see that his first assumption was wrong. 

I had to solve this dramatically as a response to your initial behavior. Since you have said that was not what you meant, I now have offer a working solution, but you refused, that's fine, just less work for me. 

I want to limit the time I need to spend on the project to 30 minutes per day. I have other things to do and the project starts to be a heavy task. Every issue that is opened needs to be tested, and people kept complaining about us not supporting Adguard. At the end, the project is more for myself, and maybe 100 other people who are using the same setup, it was never intended to be included in any ad blocker by default.

**Comment by jspenguin2017** [comment]
Oh, BTW, this also shows how vulnerable your software is, you are adding so many filter lists to your settings page, it only take one list to be compromised to have some cross site scripting. You should limit the script rule to your official filter lists only.

**Comment by ameshkov** [comment]
> you are adding so many filter lists to your settings page, it only take one list to be compromised to have some cross site scripting.

It affected only those who installed the filter from direct URL. If a user picks a filter from the known filters list, it will be served from our server and stripped from anything suspicious -- https://filters.adtidy.org/windows/filters/237.txt

**Comment by BooBerry** [comment]
@jspenguin2017 like I expressed in my personal opinion as a general user before, people don't really read warnings and instructions other than the name of the project is Adblock Protector and it's "supposed to be a successor to Reek's Anti-Adblock Killer" (which is the general opinion of others it seems, not mine other than the first impression). The name _implies it works_ for Adblock.

Again, you might be better off renaming the list/script if you want people to stop using unsupported ad blockers and posting invalid issues using unsupported ad blockers and script managers (ala Greasemonkey and Tampermonkey).

**Comment by jspenguin2017** [comment]
@BooBerry 
Yea... I guess you are right... I might as well rename it and end this. 

I didn't want to kick Adguard users out, and I didn't want to start banning users, I just want them to go through the process of finding the home page, read the instructions, and install it after knowing what may not work. I was surprised that the developers refuse to remove the entry as I expected it to be trivial task. 

Whatever happened doesn't matter, we ended up here and I'm fine with it.

**Comment by BooBerry** [comment]
It shouldn't be too difficult to get @gorhill to change the filter option within uBO by opening an issue on his repo or wherever.

@ameshkov you guys will likely have to change the placeholder entry in regards to the renaming and changed link to prevent users from installing the filter (why they would after the rename, is beyond me).

But yeah, it's probably for the best.

**Comment by uBlock-user** [comment]
> I know you're helping the guy

@ameshkov First, a correction, I'm not helping that "guy" or any "guy" on github, I contribute to his repository specifically because it supports uBO and I'm a uBO user as you're well aware of. Secondly, you can't expect everyone to have enormous amount of patience, close each and every invalid issue and what not just because some users are typically careless and simply won't bother to read the contribution guideline.

I have observed Smed79's behavior for a long time and that guy has a nasty habit of helping everyone anyway possible and you might be thinking how's that nasty ? For example, he will post ABP - compatible filters where he opens connections to ad-servers by white-listing just to hide or kill ads in uAssets repo which is for specific uBO filters only, but yet he will do it anyway without having any second thoughts.

Another thing is he's a smart guy compared to the load of imbeciles I have came across, but yet as @jspenguin2017 mentioned, he opened a pull request without bothering to read the home-page where it explicitly states that only uBO is supported and then complained about  the Script not supporting all adblockers. Now I don't know what's wrong with him, either he didn't bother to read the homepage of the website which is his fault OR he misunderstood the language as English is NOT his first language or he was being an idiot and simply opened pull request, who knows ? Personally I don't care, but the fact of matter remains this becomes annoying and frustrating for @jspenguin2017 and you CANNOT expect him to have patience and deal with people now coming to his repository and dropping issues like flies. No. Not everyone is going to be patient and you will have to accept that.

Lastly, please don't lump me with anyone just because I "contribute" to his/her repository. I have contributed to your adguard filters repo too and have contributed to 11 more repo besides yours and AdBlock Protector, so I'm not taking anyone's side here, but only justifying the situation that has developed here.

TL;DR - He was expecting a quick and a prompt end to his issue and while the problem here escalated to an extent that he lost his patience, so if it was handled quickly and in a satisfactory way, this horde of arguments wouldn't have happened. That's all.

**Comment by ameshkov** [comment]
@uBlock-user 

I have no problem with his repo, it is his product and his rules. If you read the discussion above, you'll see that the situation was resolved.

I have a problem with his attitude. It is not okay to disrespect others, it is absolutely unacceptable to get revenge for anything on common people who have no freaking idea on what's going on.

> Smed79
Comments to that pull requests were edited, so you just don't see what pissed me off. Anyways, that was just the last straw.

@BetaLeaf asked me to mention him here because it appears that my accidental lock/unlock in the very beginning left the issue in some kind of a semi-locked state.

**Comment by uBlock-user** [comment]
> Comments to that pull requests were edited,so you just don't see what pissed me off.

There's only one edited comment, so do you have any picture proof with you ?

**Comment by ameshkov** [comment]
> There's only one edited comment, so do you have any picture proof with you ?

And the Smed79's answer removed. Nothing too serious, though, just one more "garbage" mention.

Let me please emphasize one thing -- I don't have a problem with @jspenguin2017. As I've said, it is his product, his rules, he does a good thing after all. Heck, I don't mind helping to resolve some issues even now. When I did it last time I was well-aware that he does not support AG and I don't care because the issue research/resolution benefits everybody.

However, since this revenge thing happened, I figured that I cannot trust AP/UP as a user, that's why I won't recommend it to anybody. Please note, that I am talking about recommending/mentioning, we will never prevent people from using anything, this is their choice.

**Comment by uBlock-user** [comment]
I removed that question because after posting it I felt that I'm also getting caught up into that further and it might just further escalate which wasn't the purpose . Anyways, this has gone far as it should, so I recommend you locking this up for good as there's nothing more left to discuss and just move on, there's no point on dwelling on this.
