### ISSUE TITLE
Specify why filtering is paused

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardBrowserExtension#717]
Not sure what you guys think about that, but I would find it useful to see a hint why the protection is paused (e.g. it's a banking site and therefore excluded from filtering etc.)
If that is possible though.

![image](https://cloud.githubusercontent.com/assets/10995998/26590119/133aede6-455a-11e7-8ff1-7fc95b682008.png)

Adguard for Windows: 6.2.357.1887
Chrome browser extension: 2.6.3

**Comment by vozersky** [comment]
@danidoedel @Bohdan-SUP you can only see this message if you've actually paused the protection yourself:
![screen shot 2017-05-31 at 18 13 59](https://cloud.githubusercontent.com/assets/17472907/26639324/2b4bd9d0-462d-11e7-8992-59618b89ef21.png)

**Comment by danidoedel** [comment]
@vozersky Yeah true, that was stupid :D

But if that site is excluded by exclusion list, the filtering of the extension is still active. Is that the expected behavior? If so, it seems a bit odd and misleading.

And if I stop filtering via Adguard for Windows, the extension still filters every website. Not sure, but shouldn't they share the filtering state/setting?

**Comment by vozersky** [comment]
@danidoedel Sorry for the late reply! Yes, it's actually an expected behaviour at the moment, browser extension determines if it has to work in the integration mode by the header sent by the desktop app. And if the page is in HTTPS exclusions the app doesn't filter it at all, so it can't add the header. 
So, to change this behaviour we will have to completely change the way integration mode works in the browser extension.

**Comment by vozersky** [comment]
You don't really need the browser extension if you use the app though, Adguard Assistant does absolutely the same.
