### ISSUE TITLE
Page loading time affected

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#836]
In the new web extension page loading time is slow compared to legacy version. I only check on YouTube and Torrent site. Response time of Adguard layout is also slow. Clicking on "Check for filter updates" consume too much ram and not releasing properly after update complete. 

Your environment

Adguard AdBlocker extension version: 2.7.0 beta
Environment name and version: Nightly FF 57
Filters you use in Adguard : English filter, Spyware filter, Social media filter, Annoyances filter, EasyPrivacy, Fanboy's Annoyances
Any other browser extensions you have installed: NO

**Comment by ameshkov** [comment]
WebExtensions API itself is a wrapper over legacy APIs, so no surprise here:(.

**Comment by Anoop2609** [comment]
What! Then when the pure web extenstion is coming?

**Comment by Anoop2609** [comment]
Ram consumption is also increased with the adguard compare to without adguard.

**Comment by Anoop2609** [comment]
On Nightly FF 57, In memory comparison adguard Web-extension consuming 25MB more than uBlock Origin Web-extension

**Comment by Anoop2609** [comment]
@ameshkov if WebExtensions API itself is a wrapper over legacy APIs so why is uBlock origin is performing better than adguard on all standards

**Comment by ameshkov** [comment]
> In the new web extension page loading time is slow compared to legacy version. I only check on YouTube and Torrent site.

There's a 100-200ms delay due to CSS applied to the page. I hope it'll go away once we implement #847 

> On Nightly FF 57, In memory comparison adguard Web-extension consuming 25MB more than uBlock Origin Web-extension

I can confirm that uBO consumes ~10-15MB less memory on both Chrome and FF. It seems that he did a great optimization recently as there was no difference a couple of months ago. Thumbs up, I am impressed. The main reason for it is that we store compiled filters in a different format. Unlike uBO, we store original rules strings as well. This is an overhead indeed, but on the other hand, it allows us to quickly change filters when you edit the user filter or add a custom rule. However, the memory usage does not and cannot affect page loading speed. We'll think how to further shrink the filtering engine memory to keep pace with uBO. Thank god it exists, good motivation:)

> Clicking on "Check for filter updates" consume too much ram and not releasing properly after update complete.

There's no memory leak. But it seems that there're too many memory allocations, so FF needs quite a few GC cycles to clean it up.

Good catch, thank you!

Filed a separate issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/848

**Comment by The-Commissioner** [comment]
I think you guys are highly understating the difference in memory.
15-20MB I feel at startup only without any pages open. :-)

**Comment by Anoop2609** [comment]
yes, 15-20 MB on startup but when we open 15 tabs in FF memory difference increase exponentially. Not really exponentially but there is some serious work required in the field code optimization.

**Comment by The-Commissioner** [comment]
It doesn't even pick up all the images when using block element from page context menu.

**Comment by Anoop2609** [comment]
If you think there are some really good feature in ABP + EHH. Can list them and fill an issue? If those feature is possible to implement then i am sure @ameshkov will take care of them. I will give them a try.

**Comment by The-Commissioner** [comment]
> Can list them and fill an issue?

I can but I won't. It's complicated. :-D
