### ISSUE TITLE
Add "Filter" column to the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#863]
Here's what needs to be done:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/862#issuecomment-331571508

The new column must be placed after the "Filtering rule"

**Comment by Nzzyme** [comment]
@ames
I think there is a misunderstanding with this issue, It was raised so that there is an additional column with the name of the filter subscription like 'AdGuard Base filter', 'AdGuard Mobile Ads filter', etc. shown in the Filtering Log rather than the actual rule itself.

Can you confirm if it was the case and the idea was dropped?

**Comment by ameshkov** [comment]
@Nzzyme why dropped? There is a "Filter" column now in the filtering log

**Comment by Nzzyme** [comment]
Oh yes, I see it now. My bad :)
