### ISSUE TITLE
Cannot unblock "Tab for a Cause"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#875]
Source report:
https://twitter.com/sara_s_thoughts/status/916454235579080704

Steps to reproduce:
1. Install the chrome extension
2. Navigate to a new tab
3. All the ads are blocked there

The thing is, that there is no possibility to unblock it.

**Comment by Mizzick** [comment]
<img width="375" alt="screenshot 2017-10-11 11 29 09" src="https://user-images.githubusercontent.com/13855288/31429708-6b43d4ae-ae77-11e7-9fae-75b34c512488.png">
In extension we have "Protection on this site" button, which works fine.
Also rules could be whitelisted on Log page.

I don't clear understand what is the problem here?

**Comment by ameshkov** [comment]
"Tab for a Cause" replaces your "newtab" tab, which you cannot control with AG.

However, the ads are still blocked there.

**Comment by Mizzick** [comment]
ahhh, okay

**Comment by Mizzick** [comment]
Partially the issue could be solved with
`@@|http$domain=tab.gladly.io,third-party`
But it seems to be impossible to whitelist it fully until we fix #881

**Comment by ameshkov** [comment]
Got it, closing then
