### ISSUE TITLE
Is there an option to force allowing blocking on all the websites?

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardBrowserExtension#887]
On a few websites like iTunes, JetBrains etc. Adguard doesn't allow to block stuff because it thinks that blocking will 'interfere with website's working'.

While I don't really understand what exactly could be broken with exactly these websites, is there at least a 'superuser'-like mode for the ones hoping that everything would remain somewhat OK even if they try to block stuff on such websites (like me)?

If there's not, I'd really love to have one, because now I have to use AdBlock along with Adguard to just block stuff on that couple of websites. And it seems to work well BTW :D

**Comment by LaaUnique** [comment]
Having thought about it a bit more I guess (especially having PayPal in the list) that the reason is primarily financial security for trusted services, but..... stil I'd like to block a couple of things there :)
BTW is there a complete list of such websites?

**Comment by vozersky** [comment]
Hi!

Those exceptions are located in filters, i.e. [English filter](https://filters.adtidy.org/extension/chromium/filters/2.txt): "@@||paypal.com^$document" <- paypal exception rule. And since you can't edit (disable rules) in our browser extension filters lists it is not possible to override those exceptions atm. However in Adguard 2.8 we are going to add an `$badfilter` modifier and it will become possible :)

**Comment by levonder** [comment]
👏 👏
