### ISSUE TITLE
Add button in menu for a single-click ad report of a website [feature request]

### ISSUE THREAD

**Issue by stivens13** [AdguardTeam/AdguardBrowserExtension#960]
At the moment, you need to click on "Submit a complaint on about this website" and fill out 8 forms (if you report using this button, some of the forms are pre-filled, but try just to report without redirect). This is excessive and verbose.

I propose to add another button (the current one is still useful for general cases) for specific ad report on a website. When user clicks on it, extension can take a screenshot of current page (optional) and send all the info that extension already has - its version, browser info, and link to the website.

This is simplified and more effective ad reporting system (or extension of current). User doesn't even need to be redirected to report website.

**Comment by ameshkov** [comment]
@stivens13 hi! This is how things were before we added the reports.adguard.com webapp.

The point is that the old way didn't provide any real value to us. Filters maintainers **need** to see and know more than just what can be provided automatically.

And there's more to it. Most of these single-click reports seem to be caused by malicious browser extensions that inject ads. We simply cannot reproduce such an issue on our side.

**Comment by ameshkov** [comment]
> When user clicks on it, extension can take a screenshot of current page (optional) and send all the info that extension already has - its version, browser info, and link to the website.

This one is worth a separate feature request though.
